### ISSUE TITLE
Document resource operation pattern matching

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#169]
Ignore from the build:

```toml
[build.resources.ignore]
includes = ["/assets/css/theme.css"]
```

Force the symlink behavior:

```toml
[build.resources.symlink]
includes = ["/assets/css/theme.css"]
```

Force a file to be copied:

```toml
[build.resources.copy]
includes = ["/assets/css/theme.css"]
```
