### ISSUE TITLE
Support link settings

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#18]
To control aspects of the link behavior, suggestions:

```toml
[link]
# The link helper verifies link paths
verify = true
# The link helper makes URLs relative
relative = true
# Use `index.html` paths for directories
include-index = false
```
