### ISSUE TITLE
Document menu support

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#193]
How to define menus in the page data and how to render them using the helper.

## Configure

Example for `site.toml` to configure menus available to all pages:

```toml
[page.menu]
main = {file = "MAIN_MENU.md"}
sidebar = {paths = ["/docs/", "/faq/"]}
```

Currently menus can come from a single file template using `file` or from a series of page references (`paths`), later we aim to support nested menus and glob pattern matching for more powerful menus.

Requires work to verify we can disable menus for specific pages (unset global menus) which would be useful.

## Render

Then they can be rendered by id by calling the helper:

```handlebars
{{menu "main"}}
{{menu "sidebar"}}
```

Rendering can be in the layout or a specific page.

/cc @chrism
