### ISSUE TITLE
Support profiles

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#24]
A profile can be triggered using the --tag= command, when it is set the default arguments should be loaded from a profile configuration.

This will allow stuff like:

```toml
[profile.dist]
include-index = true
```

Then we can trigger the profile using:

```
ht --release --tag=dist
```
