### ISSUE TITLE
Support glob patterns in pages map

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#259]
So we can assign layouts to lots of files like this:

```toml
[pages."/docs/**/**"]
layout = "docs"
```
