### ISSUE TITLE
Remove feed helper

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#275]
The feed collation logic should create these `<link>` elements for pages that match.

Extend the feed configuration with glob matches of pages to create `<link rel="alternate">`, eg:

```toml
[feed.posts]
...
alternate = ["/", "/posts/**/**"]
```
