### ISSUE TITLE
Make incremental builds an opt-in feature

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#31]
It can be confusing to see lots of `noop` for people new to hypertext and incremental builds are only really beneficial for extremely large sites so put them behind a feature flag. Suggestion:

```toml
[build]
incremental = true
```
