### ISSUE TITLE
Support custom compute folders for plugins

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#427]
We could let plugins do something like this:

```toml
[compute.partials]
from = "site/partials"
``` 

Edit: actually as we know the type of the plugin is `blueprint` we can switch the automatic plugin compute logic to look inside the `site` folder automatically :+1:  

So that the computed plugin logic would make partials available from sites using the `blueprint` type. All we need then is to prevent certain files being copied over during project creation from a blueprint:

```toml
[[blueprint.ignores]]
path = "site/partials/*.hbs"
```

Then a new project created from a partial would be able to use the partials from the blueprint plugin by default - as always they would be able to override them the usual way.

/cc @chrism
