### ISSUE TITLE
Fix transient dependencies

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#438]
The plugin `std::blueprint::blog` now depends upon `std::paginate` but when the `blog` site runs which depends upon `std::blueprint::blog` it generates an error because the `std::paginate` dependency is not being made available.

A temporary workaround is to add the transient dependency directly:

```toml
[dependencies."std::paginate"]
version = "^1"
apply = { styles = ["**"] }
```
